# Generated by Django 4.1.7 on 2025-11-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('gerente', 'Gerente'), ('admin_sistema', 'Administrador Sistema')], default='cliente', max_length=20),
        ),
    ]
