# Generated by Django 4.1.7 on 2025-12-10 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_cliente_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (Imgur, Cloudinary, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SolicitudAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20)),
                ('tipo_solicitud', models.CharField(choices=[('cambio_stock', 'Cambio de Stock'), ('nuevo_producto', 'Nuevo Producto'), ('modificar_precio', 'Modificar Precio'), ('eliminar_producto', 'Eliminar Producto')], db_index=True, max_length=50)),
                ('modelo_afectado', models.CharField(max_length=100)),
                ('id_objeto_afectado', models.CharField(blank=True, max_length=255, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict, null=True)),
                ('motivo', models.TextField()),
                ('comentario_respuesta', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('ip_solicitante', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('producto_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='inventario.producto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Autorización',
                'verbose_name_plural': 'Solicitudes de Autorización',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito'), ('efectivo', 'Efectivo')], default='transferencia', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='inventario.cliente')),
                ('vendedor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_vendedor', to='inventario.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallesPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo_accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('APROBACION_SOLICITUD', 'Aprobación de Solicitud'), ('RECHAZO_SOLICITUD', 'Rechazo de Solicitud'), ('CREACION_SOLICITUD', 'Creación de Solicitud'), ('ACTUALIZACION_STOCK_AUTOMATICA', 'Actualización Automática de Stock')], db_index=True, max_length=50)),
                ('modelo', models.CharField(choices=[('Producto', 'Producto'), ('Categoria', 'Categoría'), ('Cliente', 'Cliente'), ('Pedido', 'Pedido'), ('AuditLog', 'Log de Auditoría'), ('SolicitudAutorizacion', 'Solicitud de Autorización')], db_index=True, max_length=50)),
                ('id_objeto', models.CharField(db_index=True, max_length=255)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict, null=True)),
                ('descripcion', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('hash_integridad', models.CharField(blank=True, max_length=64, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='inventario__estado_674b53_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['solicitante', '-fecha_solicitud'], name='inventario__solicit_9d86c2_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['tipo_solicitud', 'estado'], name='inventario__tipo_so_9427f5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['fecha'], name='inventario__fecha_5df2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tipo_accion'], name='inventario__tipo_ac_303004_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['modelo'], name='inventario__modelo_e0cc38_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['usuario'], name='inventario__usuario_eff0d8_idx'),
        ),
    ]
