# Generated by Django 5.2.7 on 2025-11-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_cliente_fecha_nacimiento_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (Imgur, Cloudinary, etc.)', null=True),
        ),
    ]
