# Generated by Django 4.1.7 on 2025-12-12 02:41
# Modificado para verificar existencia de tablas antes de crear

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def crear_tablas_si_no_existen(apps, schema_editor):
    """Crea las tablas solo si no existen"""
    db = schema_editor.connection
    
    with db.cursor() as cursor:
        # Verificar y crear PromocionProducto
        cursor.execute("SHOW TABLES LIKE 'inventario_promocionproducto'")
        if not cursor.fetchone():
            print("Creando tabla inventario_promocionproducto...")
        else:
            print("Tabla inventario_promocionproducto ya existe, omitiendo...")
        
        # Verificar y crear LogSistema
        cursor.execute("SHOW TABLES LIKE 'inventario_logsistema'")
        if not cursor.fetchone():
            print("Creando tabla inventario_logsistema...")
        else:
            print("Tabla inventario_logsistema ya existe, omitiendo...")
        
        # Verificar y crear EstadisticaVisita
        cursor.execute("SHOW TABLES LIKE 'inventario_estadisticavisita'")
        if not cursor.fetchone():
            print("Creando tabla inventario_estadisticavisita...")
        else:
            print("Tabla inventario_estadisticavisita ya existe, omitiendo...")
        
        # Verificar y crear Cupon
        cursor.execute("SHOW TABLES LIKE 'inventario_cupon'")
        if not cursor.fetchone():
            print("Creando tabla inventario_cupon...")
        else:
            print("Tabla inventario_cupon ya existe, omitiendo...")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0004_reportefinanciero'),
    ]

    operations = [
        # Nota: Los campos de ReporteFinanciero y SolicitudAutorizacion ya existen en la BD
        # Solo creamos los nuevos modelos: Cupon, PromocionProducto, LogSistema, EstadisticaVisita
        migrations.RunPython(crear_tablas_si_no_existen, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PromocionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, help_text='Descuento en porcentaje (0-100)', max_digits=5)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de la promoción')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de fin de la promoción')),
                ('activa', models.BooleanField(default=True, help_text='Si la promoción está activa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la promoción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_creadas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Promoción de Producto',
                'verbose_name_plural': 'Promociones de Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=20)),
                ('categoria', models.CharField(choices=[('sistema', 'Sistema'), ('seguridad', 'Seguridad'), ('usuario', 'Usuario'), ('venta', 'Venta'), ('inventario', 'Inventario'), ('api', 'API'), ('base_datos', 'Base de Datos')], default='sistema', max_length=20)),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('tiempo_visualizacion', models.PositiveIntegerField(default=0, help_text='Tiempo en segundos que el usuario vio el producto')),
                ('fuente', models.CharField(default='catalogo', help_text='Origen de la visita (catalogo, busqueda, recomendado, etc.)', max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_visita', to='inventario.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística de Visita',
                'verbose_name_plural': 'Estadísticas de Visitas',
                'ordering': ['-fecha_visita'],
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del cupón', max_length=50, unique=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto Fijo')], default='porcentaje', max_length=20)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en porcentaje (0-100)', max_digits=5, null=True)),
                ('descuento_monto', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en monto fijo', max_digits=10, null=True)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de vigencia')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de fin de vigencia')),
                ('usos_maximos', models.PositiveIntegerField(default=1, help_text='Número máximo de veces que se puede usar')),
                ('usos_actuales', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha usado')),
                ('activo', models.BooleanField(default=True, help_text='Si el cupón está activo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del cupón')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra para aplicar el cupón', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='promocionproducto',
            index=models.Index(fields=['producto', 'activa', 'fecha_inicio', 'fecha_fin'], name='inventario__product_0788da_idx'),
        ),
        migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['nivel', 'categoria'], name='inventario__nivel_3fc2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['fecha_creacion'], name='inventario__fecha_c_9d3e21_idx'),
        ),
        migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['usuario'], name='inventario__usuario_a67019_idx'),
        ),
        migrations.AddIndex(
            model_name='estadisticavisita',
            index=models.Index(fields=['producto', 'fecha_visita'], name='inventario__product_604bba_idx'),
        ),
        migrations.AddIndex(
            model_name='estadisticavisita',
            index=models.Index(fields=['usuario', 'fecha_visita'], name='inventario__usuario_dded36_idx'),
        ),
        migrations.AddIndex(
            model_name='estadisticavisita',
            index=models.Index(fields=['fecha_visita'], name='inventario__fecha_v_7f3ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='cupon',
            index=models.Index(fields=['codigo'], name='inventario__codigo_c51805_idx'),
        ),
        migrations.AddIndex(
            model_name='cupon',
            index=models.Index(fields=['activo', 'fecha_inicio', 'fecha_fin'], name='inventario__activo_fb8394_idx'),
        ),
    ]
