# Generated by Django 4.1.7 on 2025-12-12 03:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0005_crear_cupones_promociones'),
    ]

    operations = [
        # Campos de ReporteFinanciero y SolicitudAutorizacion ya existen en la BD
        # Solo creamos los modelos de Reclamos
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('entrega', 'Entrega'), ('servicio', 'Servicio'), ('pago', 'Pago'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('titulo', models.CharField(help_text='Título breve del reclamo', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del reclamo')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], db_index=True, default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('resolucion', models.TextField(blank=True, help_text='Descripción de la resolución del reclamo')),
                ('satisfaccion_cliente', models.IntegerField(blank=True, help_text='Calificación de satisfacción (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Usuario asignado para resolver el reclamo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='inventario.cliente')),
                ('pedido_relacionado', models.ForeignKey(blank=True, help_text='Pedido relacionado si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='inventario.pedido')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('es_interno', models.BooleanField(default=False, help_text='Si es True, solo lo ven staff. Si es False, lo ve el cliente también')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto al comentario', null=True, upload_to='reclamos/adjuntos/')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='inventario.reclamo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_reclamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Reclamo',
                'verbose_name_plural': 'Comentarios de Reclamos',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='reclamo',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='inventario__estado_426bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamo',
            index=models.Index(fields=['cliente', '-fecha_creacion'], name='inventario__cliente_7681e2_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamo',
            index=models.Index(fields=['tipo', 'prioridad'], name='inventario__tipo_2fc47f_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamo',
            index=models.Index(fields=['asignado_a', 'estado'], name='inventario__asignad_cab009_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarioreclamo',
            index=models.Index(fields=['reclamo', 'fecha_creacion'], name='inventario__reclamo_dec8ef_idx'),
        ),
    ]
