# Generated by Django 4.1.7 on 2025-12-10 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_producto_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo_accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('APROBACION_SOLICITUD', 'Aprobación de Solicitud'), ('RECHAZO_SOLICITUD', 'Rechazo de Solicitud'), ('CREACION_SOLICITUD', 'Creación de Solicitud'), ('ACTUALIZACION_STOCK_AUTOMATICA', 'Actualización Automática de Stock')], db_index=True, max_length=50)),
                ('modelo', models.CharField(choices=[('Producto', 'Producto'), ('Categoria', 'Categoría'), ('Cliente', 'Cliente'), ('Pedido', 'Pedido'), ('AuditLog', 'Log de Auditoría'), ('SolicitudAutorizacion', 'Solicitud de Autorización')], db_index=True, max_length=50)),
                ('id_objeto', models.CharField(db_index=True, max_length=255)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict, null=True)),
                ('descripcion', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('hash_integridad', models.CharField(blank=True, max_length=64, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['fecha'], name='inventario__fecha_5df2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tipo_accion'], name='inventario__tipo_ac_303004_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['modelo'], name='inventario__modelo_e0cc38_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['usuario'], name='inventario__usuario_eff0d8_idx'),
        ),
    ]
