# Generated by Django 4.1.7 on 2025-12-10 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0007_auditlog_auditlog_inventario__fecha_5df2b6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20)),
                ('tipo_solicitud', models.CharField(choices=[('cambio_stock', 'Cambio de Stock'), ('nuevo_producto', 'Nuevo Producto'), ('modificar_precio', 'Modificar Precio'), ('eliminar_producto', 'Eliminar Producto')], db_index=True, max_length=50)),
                ('modelo_afectado', models.CharField(max_length=100)),
                ('id_objeto_afectado', models.CharField(blank=True, max_length=255, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict, null=True)),
                ('motivo', models.TextField()),
                ('comentario_respuesta', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('ip_solicitante', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('producto_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='inventario.producto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Autorización',
                'verbose_name_plural': 'Solicitudes de Autorización',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='inventario__estado_674b53_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['solicitante', '-fecha_solicitud'], name='inventario__solicit_9d86c2_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['tipo_solicitud', 'estado'], name='inventario__tipo_so_9427f5_idx'),
        ),
    ]
