# Generated by Django 4.1.7 on 2025-12-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_reportefinanciero_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='inventario.direccionenvio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(blank=True, choices=[('estandar', 'Envío Estándar (3-5 días)'), ('express', 'Envío Express (1-2 días)'), ('retiro_tienda', 'Retiro en Tienda (Gratis)')], max_length=20, null=True),
        ),
    ]
