# Generated by Django 4.1.7 on 2025-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_pedido_costo_envio_pedido_direccion_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefinanciero',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportefinanciero',
            name='enviado_por_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportefinanciero',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportefinanciero',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudautorizacion',
            name='comentario_revision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportefinanciero',
            name='emails_destino',
            field=models.TextField(blank=True, help_text='Emails separados por comas'),
        ),
        migrations.AlterField(
            model_name='reportefinanciero',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='completado', max_length=20),
        ),
    ]
